### PR TITLE
Add script to re-generate PACs

### PR DESCRIPTION
**Pull request by dbrgn**
Here's a script to re-generate the PACs with the current svd2rust version.

Currently only 2 of the 3 PACs are set up. For PAC to be generated, the following items are required:

- It needs to be registered below in the `PACS` array.
- The directory needs to contain an SVD file with the name matching the crate name.

I also commited the generated output so you can see the result of the script, but we can also move the commit to a separate pull request once the generate.sh script is fleshed out.

@hannobraun I saw that your crate splits up the library into multiple modules. That's very nice, how did you do it? We can also add it to the script.

Comments of any kind are welcome :slightly_smiling_face:

### CODE REVIEW

**Comment by hannobraun** [comment]
I haven't had time for a review yet. I've added it to my list.

@dbrgn 
> I saw that your crate splits up the library into multiple modules. That's very nice, how did you do it? We can also add it to the script.

I did that using the [form](https://crates.io/crates/form) utility. See the [lpc82x update script](https://github.com/lpc-rs/lpc-pac/blob/37585a7d0ce5aad8386b91b186d4a2eb31a1456e/lpc82x/scripts/update.sh) for details.

**Comment by dbrgn** [comment]
Oh, nice. I'll integrate `form`.

**Review by hannobraun — APPROVED** [review]
I haven't reviewed the generated code, but everything else looks good to me!

I'm not merging this PR in case anyone wants to test the re-generated PACs (I don't have hardware for those two). However, if any of you want to merge it, you have my approval.

Thank you @dbrgn, great work!

**Comment by dbrgn** [comment]
@rnestler do you have the LPC devboard with you?

**Comment by rnestler** [comment]
> @rnestler do you have the LPC devboard with you?

No sadly not :(

**Comment by dbrgn** [comment]
Let's just regenerate and merge :slightly_smiling_face:

**Pull request merged**
