### PR TITLE
Fix generate script issues

### PR DESCRIPTION
**Pull request by rnestler**
Found with the shellcheck utility.

### CODE REVIEW

**Comment by rnestler** [comment]
Should I add a CI step to run shellcheck on the generate script?

**Comment by dbrgn** [comment]
"Fix type in comment" - haha, is that on purpose?

**Review by dbrgn — APPROVED** [review]
Looks good to me, except for the typo in the typo fix commit.

Also, "Fix lots of Quote to prevent word splitting issues" looks strange :slightly_smiling_face: 

But maybe we can squash the commits, then it doesn't matter.

**Comment by rnestler** [comment]
> "Fix type in comment" - haha, is that on purpose?

Well I spellchecked it and it didn't show up as wrong :stuck_out_tongue_closed_eyes: 

> Also, "Fix lots of Quote to prevent word splitting issues" looks strange slightly_smiling_face

That's the output from shellcheck: "Quote this to prevent word splitting". I should probably have quoted it in the commit message :laughing: 

> But maybe we can squash the commits, then it doesn't matter.

Probably easier :wink:

**Pull request merged**
