### PR TITLE
Add LPC54606 PAC

### PR DESCRIPTION
**Pull request by hannobraun**

### CODE REVIEW

**Comment by hannobraun** [comment]
I've just published the crate: https://crates.io/crates/lpc54606-pac

Guess I'll have to do some quick editing of the repository link, in case anyone objects to adding it here :-)

**Review by dbrgn — APPROVED** [review]
No objections from my side :slightly_smiling_face: 

What does the `device.x` file do? I'm not familiar with that yet. Is it a svd2rust thing?

**Comment by dbrgn** [comment]
Ah, and does the PAC cover exactly the 54606 series, or might we "wildcard" some parts of the name like with lpc11uxx or lpc82x?

**Comment by hannobraun** [comment]
> What does the `device.x` file do? I'm not familiar with that yet. Is it a svd2rust thing?

That's an svd2rust thing. It's processed in the build script, I believe, but I haven't looked into the details recently.

> Ah, and does the PAC cover exactly the 54606 series, or might we "wildcard" some parts of the name like with lpc11uxx or lpc82x?

It's generated from the LPC54606 SVD file, and there are different files for other models, like LPC54608, for example. I haven't compared those files, so I can't answer your question.

I don't want to spend a whole lot of time on this right now, so I figured doing something limited is better than not doing anything because of perfectionism.

**Comment by hannobraun** [comment]
Okay, I'm merging this. I guess adding more PACs isn't a controversial change anyway.

**Pull request merged**
