### PR TITLE
Update svd2 rust

### PR DESCRIPTION
**Pull request by axos88**
Update to newest svd2rust version and regenerate all code.

(!) merge #35 first.

### CODE REVIEW

**Comment by axos88** [comment]
I have no idea why svd2rust is generating that trailing underscore for the `match_`. Do you think this is a regression in svd2rust?

**Comment by hannobraun** [comment]
@axos88 
> I have no idea why svd2rust is generating that trailing underscore for the `match_`. Do you think this is a regression in svd2rust?

I don't know if this was handled in a different way previously, but `match` is a keyword and using it as a name for anything won't compile. The underscore is probably there to prevent this problem.

**Comment by axos88** [comment]
> @axos88
> 
> > I have no idea why svd2rust is generating that trailing underscore for the `match_`. Do you think this is a regression in svd2rust?
> 
> I don't know if this was handled in a different way previously, but `match` is a keyword and using it as a name for anything won't compile. The underscore is probably there to prevent this problem.

Nope, if that was the case [raw identifiers](https://doc.rust-lang.org/edition-guide/rust-2018/module-system/raw-identifiers.html) could be used

**Comment by hannobraun** [comment]
> Nope, if that was the case [raw identifiers](https://doc.rust-lang.org/edition-guide/rust-2018/module-system/raw-identifiers.html) could be used

I'm not aware of the reasoning for this specific design decision, but if I recall correctly, raw identifiers are only available since the 2018 edition, and svd2rust predates that by years. It's not a surprise if a design decision in svd2rust doesn't take all current language features into account.

**Comment by axos88** [comment]
> raw identifiers are only available since the 2018 edition,

You're right, didn't know this.

**Comment by hannobraun** [comment]
The svd2rust version used has been updated in #39. Closing.

**Pull request closed without merging**
